/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class YingReverbAudioProcessorEditor  : public AudioProcessorEditor, private Slider::Listener
{
public:
    YingReverbAudioProcessorEditor (YingReverbAudioProcessor&);
    ~YingReverbAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void sliderValueChanged (Slider* slider) override;
    void resized() override;
    

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    YingReverbAudioProcessor& processor;
    Slider Mix;
    Slider reverbTime;
    //ToggleButton Bypass;
    


    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (YingReverbAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
